baseurl = "https://www.chainkeepers.io"
title = "ChainKeepers"

theme = "coder-portfolio"

DefaultContentLanguage = "cs"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
 
    author = "ChainKeepers"
    title = "ChainKeepers"
    info = "Keeping DeFi just work"
    description = "ChainKeepers - Keeping DeFi just work"
    keywords = "blockchain,blog,developer,company,startup"
    # avatarurl = "images/avatar.jpg"
    hideCredits = false
    hideCopyright = false

    # Bottom sns share
    snsShare = false
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false
    enableFacebookShare = false
    enableHatenaShare = false
    enableLineShare = false
    enableLinkedInShare = false

    thumbnail = ""

    # Custom CSS
    font_css = "https://fonts.googleapis.com/css2?family=Alegreya+Sans:500,700"
    custom_css = [ ]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = ""

# [[params.social]]
#     name = "Github"
#     icon = "fab fa-github"
#     weight = 1
#     url = "https://github.com/naro143/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter"
#     weight = 2
#     url = "https://twitter.com/naro143/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fab fa-linkedin"
#     weight = 3
#     url = "https://www.linkedin.com/in/naro143/"
# [[params.social]]
#     name = "LinkedIn"
#     weight = 4
#     url = "https://www.linkedin.com/in/naro143/"

[languages]

    # [languages.en]
    #     languagecode = "en"
    #     languagename = "English" # The language name to be displayed in the selector.

    #     [languages.en.menu] # It is possible to change the menu too.

    #         [[languages.en.menu.main]]
    #             name = "About"
    #             weight = 1.0
    #             url = "about"

    #         # [[languages.en.menu.main]]
    #         #     name = "Blog"
    #         #     weight = 2.0
    #         #     url = "posts"

    #         # [[languages.en.menu.main]]
    #         #     name = "Projects"
    #         #     weight = 3
    #         #     url = "projects"

    #         [[languages.en.menu.main]]
    #             name = "We're hiring"
    #             weight = 4
    #             url = "hiring"

    #         [[languages.en.menu.main]]
    #             name = "Contact us"
    #             weight = 5
    #             url = "contact"


    [languages.cs]
        languagecode = "cs"
        languagename = "Česky"
        footercontent = "vyvíjíme keeper boty"

        # [language.cs.params]
        #     fixedbarContent = "Hledáme posily; v případě zájmu => mailto:ondrej [at] chainkeepers [dot] io"
        #     # fixedbarContentAfter = "Thank You! Please share it if you like it→"

        [languages.cs.menu]

            [[languages.cs.menu.main]]
                name = "O NÁS"
                weight = 1.0
                url = "cs/about"

            # [[languages.cs.menu.main]]
            #     name = "Blog"
            #     weight = 2.0
            #     url = "cs/posts"

            # [[languages.cs.menu.main]]
            #     name = "Projekty"
            #     weight = 3
            #     url = "cs/projects"

            [[languages.cs.menu.main]]
                name = "HLEDÁME POSILY"
                weight = 4
                url = "cs/hiring"

            [[languages.cs.menu.main]]
                name = "KONTAKT"
                weight = 5
                url = "cs/contact"
